### PR TITLE
Added Experimentation Tracking.

### PR DESCRIPTION
**Pull request by hnhnarek**
Added Experimentation Tracking using Aim.

Now you can:

Track all the model hyperparameters and architectural choices.
Track all types of losses.
Filter all the experiments with respect to hyperparameters or the architecture
Group and aggregate w.r.t. all the trackables to dive into granular experimentation assessment.
Track the generated images to track how the model improves.

Screen Shot 2022-04-12 at 16 56 35

Screen Shot 2022-04-12 at 16 57 24

### CODE REVIEW

**Comment by lucidrains** [comment]
@hnhnarek Hey Narek! This is so awesome!

Want to write up something in the README on how to use it?

**Comment by hnhnarek** [comment]
> @hnhnarek Hey Narek! This is so awesome!
> 
> Want to write up something in the README on how to use it?

@lucidrains Hey Phil, thanks for the suggestion! I've already made the changes you suggested.

**Comment by lucidrains** [comment]
@hnhnarek 🔥🔥🔥

**Comment by lucidrains** [comment]
Thank you for this!

**Comment by hnhnarek** [comment]
@lucidrains thank you, too. I appreciate the quick review and response! Thanks for your time. ❤️

**Pull request merged**
